### ISSUE TITLE
[RT] Trouble embedding ExpressionAtlasHeatmap  React component

### ISSUE THREAD

**Issue by ke4** [ebi-gene-expression-group/atlas-components#152]
RT ticket link: https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=750267

Summary from the RT ticket:
I'm trying to include ExpressionAtlasHeatmap in my React site, but it doesn't locate the necessary resources for the anatomogram (and possibly other things). In the past I have used an iFrame to load the widget, but within that interface the anatomogram stopped working on gramene.org. This also fails to load on EnsemblPlants. For example: https://plants.ensembl.org/Oryza_sativa/Gene/ExpressionAtlas?g=Os01g0100900;r=1:35623-41136;t=Os01t0100900-01

**Comment by ke4** [comment]
@lingyun1010 Could you please have a look at this user issue, please?
Many thanks

**Comment by lingyun1010** [comment]
It's not our website issue, as It seems the specific gene search is working on our website: [SPL1](https://www.ebi.ac.uk/gxa/search?geneQuery=%5B%7B%22value%22%3A%22SPL1%22%2C%22category%22%3A%22symbol%22%7D%5D&species=&conditionQuery=%5B%5D&bs=%7B%22arabidopsis%20thaliana%22%3A%5B%22ORGANISM_PART%22%5D%2C%22oryza%20sativa%22%3A%5B%22ORGANISM_PART%22%5D%7D&ds=%7B%22kingdom%22%3A%5B%22plants%22%5D%7D#baseline).

I also made some other suggestions in the RT.
