### ISSUE TITLE
[Chore] Experiment page bundle refactoring

### ISSUE THREAD

**Issue by ke4** [ebi-gene-expression-group/atlas-components#171]
Most of the code that can be found under the experiment page bundle in the `Single Cell Expression Atlas` repository is not belongs to that repository. It should be moved to the `atlas-components` repository by creating 1 or more new components and creating a wrapper around that code in the `single cell` repository and render it.
There are 3 subtask for this story:
- [x] move the code from the `atlas-web-single-cell` repository under `app/src/main/javascript/bundles/experiment-page` folder to the `atlas-components` repository and creating 1 or more new components as it fits
- [x] clean the code: make it easy to maintain, testable, understandable by anyone. I added an example yesterday in Slack. (https://ebi-fg.slack.com/archives/C9P2QETJ9/p1726071369031389)
- [x] creating a wrapper in the `single cell` repository in the `app/src/main/javascript/bundles/experiment-page` folder around the new code and render it

**Comment by lingyun1010** [comment]
I will create a new PR to add tests for react router, but now I will need the base code to bugfix the heatmap sorting issue.
